version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    hostname: zookeeper
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog

  clickhouse01:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    volumes:
      - ./data/clickhouse01/:/var/lib/clickhouse
      - ./conf/clickhouse01:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse02:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    volumes:
      - ./data/clickhouse02/:/var/lib/clickhouse
      - ./conf/clickhouse02:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse03:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    volumes:
      - ./data/clickhouse03/:/var/lib/clickhouse
      - ./conf/clickhouse03:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse04:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.14
    volumes:
      - ./data/clickhouse04/:/var/lib/clickhouse
      - ./conf/clickhouse04:/etc/clickhouse-server
    depends_on:
      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
