version: '3.1'
services:
  zk1:
    # docker container所使用的docker image
    image: zookeeper
    hostname: zk1
    container_name: zk1
    # 配置docker container和宿主机的端口映射
    ports:
      - 2181:2181
      - 8080:8080
    # 配置docker container的环境变量
    environment:
      # 当前zk实例的id
      ZOO_MY_ID: 1
      # 整个zk集群的机器、端口列表
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    # 将docker container上的路径挂载到宿主机上 实现宿主机和docker container的数据共享
    volumes:
      - ./zk1/data:/data
      - ./zk1/datalog:/datalog
    # 当前docker container加入名为zk-net的隔离网络
    networks:
      - sgcc-network

  zk2:
    image: zookeeper
    hostname: zk2
    container_name: zk2
    ports:
      - 2182:2181
      - 8082:8080
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - ./zk2/data:/data
      - ./zk2/datalog:/datalog
    networks:
      - sgcc-network

  zk3:
    image: zookeeper
    hostname: zk3
    container_name: zk3
    ports:
      - 2183:2181
      - 8083:8080
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - ./zk3/data:/data
      - ./zk3/datalog:/datalog
    networks:
      - sgcc-network

  cs01-01:
    image: yandex/clickhouse-server
    restart: always
    container_name: cs01-01
    ports:
      - 8000:9000
      - 8123:8123
      - 9009:9009
    volumes:
      - ./data/clickhouse01-01/:/var/lib/clickhouse
      - ./conf/clickhouse-server01-01/:/etc/clickhouse-server/
    extra_hosts:
      - "server01:10.50.10.27"
      - "server02:10.50.10.27"
      - "server03:10.50.10.27"
    hostname: server01
    networks:
      - sgcc-network

  cs01-02:
    image: yandex/clickhouse-server
    restart: always
    container_name: cs01-02
    ports:
      - 9001:9000
      - 8124:8123
      - 9010:9009
    volumes:
      - ./data/clickhouse01-02/:/var/lib/clickhouse
      - ./conf/clickhouse-server01-02/:/etc/clickhouse-server/
    extra_hosts:
      - "server01:10.50.10.27"
      - "server02:10.50.10.27"
      - "server03:10.50.10.27"
    hostname: server01
    networks:
      - sgcc-network

  cs02-01:
    image: yandex/clickhouse-server
    restart: always
    container_name: cs02-01
    ports:
      - 9002:9000
      - 8125:8123
      - 9011:9009
    volumes:
      - ./data/clickhouse02-01/:/var/lib/clickhouse
      - ./conf/clickhouse-server02-01/:/etc/clickhouse-server/
    extra_hosts:
      - "server01:10.50.10.27"
      - "server02:10.50.10.27"
      - "server03:10.50.10.27"
    hostname: server02
    networks:
      - sgcc-network

  cs02-02:
    image: yandex/clickhouse-server
    restart: always
    container_name: cs02-02
    ports:
      - 9003:9000
      - 8126:8123
      - 9012:9009
    volumes:
      - ./data/clickhouse02-02/:/var/lib/clickhouse
      - ./conf/clickhouse-server02-02/:/etc/clickhouse-server/
    extra_hosts:
      - "server01:10.50.10.27"
      - "server02:10.50.10.27"
      - "server03:10.50.10.27"
    hostname: server02
    networks:
      - sgcc-network

  cs03-01:
    image: yandex/clickhouse-server
    restart: always
    container_name: cs03-01
    ports:
      - 9004:9000
      - 8127:8123
      - 9013:9009
    volumes:
      - ./data/clickhouse03-01/:/var/lib/clickhouse
      - ./conf/clickhouse-server03-01/:/etc/clickhouse-server/
    extra_hosts:
      - "server01:10.50.10.27"
      - "server02:10.50.10.27"
      - "server03:10.50.10.27"
    hostname: server03
    networks:
      - sgcc-network

  cs03-02:
    image: yandex/clickhouse-server
    restart: always
    container_name: cs03-02
    ports:
      - 9005:9000
      - 8128:8123
      - 9014:9009
    volumes:
      - ./data/clickhouse03-02/:/var/lib/clickhouse
      - ./conf/clickhouse-server03-02/:/etc/clickhouse-server/
    extra_hosts:
      - "server01:10.50.10.27"
      - "server02:10.50.10.27"
      - "server03:10.50.10.27"
    hostname: server03
    networks:
      - sgcc-network

networks:
  sgcc-network:
    external: true