version: '3'

services:
  ch_server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./db:/var/lib/clickhouse
    networks:
      - clickhouse-network

  ch_client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    networks:
      - clickhouse-network

  ch_tabix:
    image: spoonest/clickhouse-tabix-web-client
    ports:
      - "8080:80"
    networks:
      - clickhouse-network

networks:
  clickhouse-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24