version: '3.7'
services:

  hbase-master:
    image: yiluxiangbei/hbase:2.4.9
    container_name: hbase-master
    environment:
      - HBASE_NODE_TYPE=master
    volumes:
      - "./conf:/opt/hbase/conf"
      - "./logs:/opt/hbase/logs"
      - /etc/localtime:/etc/localtime
    networks:
      - sgcc-network
    ports:
      - 16000:16000
      - 16010:16010
      - 2181:2181
    restart: always

  hbase-region1:
    image: yiluxiangbei/hbase:2.4.9
    container_name: hbase-region1
    environment:
      - HBASE_NODE_TYPE=region
    volumes:
      - "./conf:/opt/hbase/conf"
      - "./logs:/opt/hbase/logs"
      - /etc/localtime:/etc/localtime
    networks:
      - sgcc-network
    ports:
      - 16020:16020
      - 16030:16030
    restart: always

  hbase-region2:
    image: yiluxiangbei/hbase:2.4.9
    container_name: hbase-region2
    environment:
      - HBASE_NODE_TYPE=region
    volumes:
      - "./conf:/opt/hbase/conf"
      - "./logs:/opt/hbase/logs"
      - /etc/localtime:/etc/localtime
    networks:
      - sgcc-network
    ports:
      - 16021:16020
      - 16031:16030
    restart: always

networks:
  sgcc-network:
    external: true